### ISSUE TITLE
gebruikers kunnen niet aangemaakt worden op de website.

### ISSUE THREAD

**Issue by njittam** [RSDT/JH-Site#1]
Error:
[10] Helaas er is iets mis gegaan tijdens het aanmaken van de gebruiker.

**Comment by Area348** [comment]
Ja er zal idd een bug in, iets met de tabel die groter geworden was, maar de invoer waarder hier nog niet^^

**Comment by Area348** [comment]
Waarom mag ik dit Issue niet closen? (mis de knop).
Mag de Naam hier van anders?
Maak dit dan Site, of JH-Site oid.
Maak ik er nu meteen 1 aan voor de API apart, 
Al vond ik het wel fijn dat alles in 1 issue gebeuren stond... scheelt een hoop geklik.

**Comment by Dingenis** [comment]
Je had nog geen rechten voor het project. Als het goed is nu wel, ik heb ook het project hernoemd naar "JH-Site" als zelf liever een andere naam hebt kan je dat als het goed is ook veranderen

**Comment by Area348** [comment]
Ja geloof dat ik nu wel de rechten heb, maar nog niet om dit issue te sluiten ;), maar inmiddels moeten gebruikers aangemaakt kunnen worden.

#close plz.
