### ISSUE TITLE
niet alle knoppen zichtbaar.

### ISSUE THREAD

**Issue by njittam** [RSDT/JH-Site#12]
is het een idee om de width van de container iets hoger te zetten dan 1000? 
in header.css

**Comment by Area348** [comment]
Gevalletje fix je brouwser.

Heb er op nog geen scherm last van gehad.
Container width > 1000 trekt gok ik de pagina uit elkaar. Width zit nog al hardcoded op veel plaatsen

**Comment by Area348** [comment]
![greenshot - 2016-10-11 08_10_08-facebook](https://cloud.githubusercontent.com/assets/14966999/19260483/303b1604-8f8a-11e6-97a8-a052bdd668f8.png)

Ik heb zelfs ruimte over!

**Comment by njittam** [comment]
![schermafdruk van 2016-10-11 20-53-28](https://cloud.githubusercontent.com/assets/6692452/19284107/d2e10818-8ff4-11e6-8212-2208a19b3279.png)

dit is firefox.
ow en ik wou laten zien dat ik in chrtome niet op mattijn kan kliken maatr dat doet t nu wel.

in firfox had ik al de lettergroote naar tiny gezet maar dat didn't fix it.

**Comment by njittam** [comment]
![schermafdruk van 2016-10-11 21-42-11](https://cloud.githubusercontent.com/assets/6692452/19285769/9cf22faa-8ffb-11e6-9a2a-a9901234541c.png)

**Comment by Area348** [comment]
Gok toch dat het ergens bij jou/linix licht^^:

**Internet Exploder:**
![greenshot - 2016-10-11 22_02_23-agenda](https://cloud.githubusercontent.com/assets/14966999/19286643/b4281a56-8ffe-11e6-97bf-a4c2374d5d25.png)

**Edge:**
![greenshot - 2016-10-11 22_03_07-agenda](https://cloud.githubusercontent.com/assets/14966999/19286644/b42887ac-8ffe-11e6-85c8-5192bf6cdf7a.png)

**Comment by njittam** [comment]
ik zie dat dit gefixt is.
