### ISSUE TITLE
Verbeteringen / ideeën volgend jaar

### ISSUE THREAD

**Issue by Area348** [RSDT/JH-Site#13]
SITE-Micky:
- [ ] ABSOLUUT de website ook auto updateable (JS) maken op de kaart ;), scheeld volgens mij enorm in de lag met het inladen.
- [ ] Openstreetmaps
  Vossen invoer pagina, met voor iedere vos een regel RD-RD, +1x tijd. !! lege invoer moet geen probleem zijn. (liefst via textarea voor copy past).
- [ ]  Coord check via bovenstaande textarea.
- [ ]  Coord check ook de optie om de dagdelen te splitsen.
- [ ]  Laatste Loc, Spot, Hunt, andere kleur dan rest van de stippen (opacity??)
- [ ]  En geen getalletjes in laten vullen door gebruiker van spots en hunts
- [ ]  Voor mattijn de site ook negatieve coords laten accepteren (site note: RD moet dan leeg blijven).
- [x] Snelheid inladen maps.

**Comment by njittam** [comment]
dulicate van RSDT/Japp#75
