### ISSUE TITLE
En geen getalletjes in laten vullen door gebruiker van spots en hunts

### ISSUE THREAD

**Issue by njittam** [RSDT/JH-Site#22]
zie RSDT/Japp#75

**Comment by Area348** [comment]
Ik snap niet wat je bedoeld met getalletjes, en vooral waar!!!!
Aangezien alleen mods iets mogen invoeren via de site.
OF bedoe je in de API?
en dan weer welke waardes bedoel je......

**Comment by njittam** [comment]
Ik heb ook geen flauw idee. misschien @Dingenis ? zo ja kan hij hem weer openen.
