### ISSUE TITLE
Voor mattijn de site ook negatieve coords laten accepteren (site note: RD moet dan leeg blijven).

### ISSUE THREAD

**Issue by njittam** [RSDT/JH-Site#23]
zie RSDT/Japp#75

**Comment by Area348** [comment]
Dit gaat niet lukken vrees ik.
Alles is gebaseerd op het feit dat we alleen in NL zitten en we daar alleen maar positieve coords kennen.
Daarnaast rekent hij alles ook meteen om naar RD, welke dan weer niet werken met negatieve coords.

In te voeren coords bereik voor onze JH site is dus effectief NL. door de voorkeur van RD gebruik!!!
