### ISSUE TITLE
whitelist werkt niet!!

### ISSUE THREAD

**Issue by njittam** [RSDT/JH-Site#24]
Ik ben bezig met de openstreetmaps op de wekaart te maken.
Daarbij is er een bug ingekomen in de login functie.

Daarbij heb ik moeten testen met een goed wachtwoord en een fout wachtwoord tijdens het debuggen.
Daardoor heb ik een ban gekregen.
Maar als ik de ip verwijder uit de banlijst en vervolgens toevoeg aan de whitelist.
Vervolgens na 1 inlog  krijg ik opnieuw een ban.wereenkt

omdat ik niet cross domain en https/http content niet kan mixen gaan alle querries via de server. dus alle querries van de website gaan over hetzelfde ip.

**Comment by Area348** [comment]
Als het goed is, is dit inmiddels gefixed.
