### ISSUE TITLE
GameOver GoogleMaps

### ISSUE THREAD

**Issue by Area348** [RSDT/JH-Site#25]
Google Maps heeft z'n dingen weer eens aangepast waardoor je nu een 'billing' moet toevoegen, en dit ga ik niet doen, de site doet het nog alleen in 'dark defelopers mode' only.

Weet nog niet of ik hier wel zin in heb om dit komend jaar helemaal om te gaan gooien naar OSM.....

**Comment by Dingenis** [comment]
Hoihoi, je krijgt 200 euro per maand gratis op een account! Je hoeft dus alleen een billing account eraan toe te voegen, maar de kosten zijn er niet.

**Comment by Area348** [comment]
Jip ik zie het, maar je moet wel een creditcard hebben om het te activeren.....
Dus nog steeds GameOver.

**Comment by Dingenis** [comment]
Ik heb een account met een creditcard gekoppelt, als je wilt kan ik even credentials voor je aanmaken zodat je dat account kan gebruiken. Zou zonde zijn als het allemaal niet werkt hierdoor, laat het mij weten groetjesss

**Comment by Area348** [comment]
Ja zat er net aan te denken, als je een key hebt kan ik deze voor deze hunt gebruiken.

**Comment by Area348** [comment]
Probleem is op gelost met een KEY van Bam ;).
Namens alle gebruikers dank ;)
