### ISSUE TITLE
scoutingroepen aanpasbaar maken.

### ISSUE THREAD

**Issue by njittam** [RSDT/JH-Site#3]
Als we in iedergeval de deelgebieden kunnen aanpassen, kunnen we nu alvast alle scoutinggroepen in de db zetten om te testen. En dan hoeven straks alleen nog maar het deelgebied aan te passen.

**Comment by Area348** [comment]
Deel gebieden zijn inmiddels via KML bestand aangepast.
@njittam is al begonnen met SC-groepen in de db te zetten.

SC-Groepen aanpasbaar maken vanavond mee begonnen maar nog niet klaar dus je krijg nu nog error's ;)

**Comment by Area348** [comment]
Fixed
