### ISSUE TITLE
opdrachten ook uploaden naar de website.

### ISSUE THREAD

**Issue by njittam** [RSDT/JH-Site#4]
Het is mischien wel leuk om een overzicht van onze eigen opdrachten op de site te hebben.

**Comment by Area348** [comment]
?
Wat bedoel je precies? 
Foto gallerij?

**Comment by njittam** [comment]
ja zoiets.

**Comment by Area348** [comment]
Ga ik nu niet meer aan beginnen, ervaring van andere jaren was niet heel goed hier mee.
