### ISSUE TITLE
crash in firefox na toevegen groepen

### ISSUE THREAD

**Issue by njittam** [RSDT/JH-Site#7]
t/m christoforus toegevoegd

**Comment by njittam** [comment]
hij vind de ' in lido '76 niet leuk.
deze moet gescaped worden.

**Comment by njittam** [comment]
SyntaxError: missing ; before statement[Learn More]map.php:335:11
mogelijk zit deze wel ook in chrome maar je moet eerst scin filter aanzetten

**Comment by Area348** [comment]
Ik snap je error niet^^

Invoer nu gestript op invoer data.

**Comment by njittam** [comment]
als die de ' in lido '76 tegenkomt denkt ie dat de string eindigt met 'lido '  en snapt niet dat 76 en alles erachter er ook nog bijhoort.

**Comment by njittam** [comment]
want nu als je scoutinggroepen aanzet op de kaart laat ie de kaart niet zien

**Comment by Area348** [comment]
Ja dat laat hij nu wel zien ;). heb de invoer al aangepast in de db. en de invoer wordt inmiddels gestript.

**Comment by njittam** [comment]
nice :)
